services:
  web:
    build: .
    ports:
      - "80:80"  # เปิดพอร์ต 80 สำหรับเว็บไซต์หลักและ phpMyAdmin
    volumes:
      - .:/var/www/html
      - ./phpmyadmin.conf:/var/www/html/realproject/phpmyadmin.conf # แผนที่ไฟล์การตั้งค่าพิเศษ
    networks:
      - app-network
    depends_on:
      - phpmyadmin  # เพื่อให้ phpMyAdmin ทำงานได้ก่อน web

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: project_maidmanage
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./project_maidmanage.sql:/docker-entrypoint-initdb.d/project_maidmanage.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: project_maidmanage
      PMA_USER: user
      PMA_PASSWORD: user_password
      PMA_PORT: 3306
    volumes:
      - ./my-httpd.conf:/var/www/html/realproject/my-httpd.conf
    command: ["apache2-foreground", "-c", "Include conf-available/my-httpd.conf"]

networks:
  app-network:
    driver: bridge