services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # ใช้เพียง port 80 ในการเข้าใช้งาน
    networks:
      - app-network
    depends_on:
      - web
      - phpmyadmin

  web:
    build: .
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: project_maidmanage
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - /var/www/html/realproject/project_maidmanage.sql:/docker-entrypoint-initdb.d/project_maidmanage.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
