services:
  web:
    build: .
    ports:
      - "80:80"  # เปิดพอร์ต 80 สำหรับเว็บไซต์หลักและ phpMyAdmin
    volumes:
      - .:/var/www/html
      - ./phpmyadmin.conf:/var/www/html/realproject/phpmyadmin.conf # แผนที่ไฟล์การตั้งค่าพิเศษ
    networks:
      - app-network
    depends_on:
      - phpmyadmin  # เพื่อให้ phpMyAdmin ทำงานได้ก่อน web

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: project_maidmanage
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password

    volumes:
      - /var/www/html/realproject/project_maidmanage.sql:/docker-entrypoint-initdb.d/project_maidmanage.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: user_password
    volumes:
      - ./phpmyadmin.conf:/var/www/html/realproject/phpmyadmin.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge